server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kafka_dashboard
    username: root
    password: 4Islamabad!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: 172.25.240.68:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


  thymeleaf:
    cache: false

kafka:
  bootstrap-servers: 172.25.240.68:9092

app:
  topic-name: test-topic
  refresh-ms: 300000 # 5 minutes

logging:
  level:
    org:
      springframework: INFO